import type { Metadata } from "next";
import "./globals.css";
import AuthHeader from "@/components/AuthHeader";
import {getUser} from "@/actions/auth/user.action";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    const user = await getUser();

    return (
        <html lang="ko" suppressHydrationWarning>
            <body>
                <AuthHeader user={user} />
                {children}
            </body>
        </html>
    );
}
